all:
	gcc -std=c99 -pedantic -Wall -Wextra -o bubblesort bubblesort.c -lm
	
	gcc -std=c99 -pedantic -Wall -Wextra -o selectionsort selectionsort.c -lm
	
	gcc -std=c99 -pedantic -Wall -Wextra -o sort sort.c -lm
	
	gcc -std=c99 -pedantic -Wall -Wextra -o randArray randArray.c -lm
